version: 1.0.{build}
os: Visual Studio 2015 RC
before_build:
  - cd src
  - nuget restore
install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build:
  verbosity: minimal
  project: LINDI.sln
