version: 1.0.{build}
environment:
  COVERALLS_REPO_TOKEN:
    secure: TODO
os: Visual Studio 2015 RC
before_build:
  - cd src
  - nuget restore
  - cd ..
install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
after_test:
  - src\packages\OpenCover.4.5.3723\OpenCover.Console.exe -target:src\packages\xunit.runner.console.2.0.0\tools\xunit.console.exe -targetargs:"LINDI.Tests.dll" -output:coverage.xml -skipautoprops -returntargetcode -filter:"+[Lindi*]* -[Lindi.Tests]*" -register:user -targetdir:"src\LINDI.Tests\bin\Debug"
  - src\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml --full-sources
build:
  verbosity: minimal
